name: CICD Test

on:
  workflow_dispatch:
    inputs:
      matrix:
        description: 'services to deploy, as an array like this: ["service1", "service2"]'
        required: true
        type: string
      test-bool:
        description: 'Rebuild changeset'
        required: true
        type: boolean
        default: true
      rebuild-all:
        description: 'Rebuild all services'
        required: true
        type: boolean
        default: false
jobs:
  check_matrix_works:
    name: Check matrix works
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJSON(inputs.matrix) }}
    steps:
      - name: Check matrix
        run: |
          echo "Matrix.service: ${{ matrix.service }}"
